VPN_CREDENTIALS_DIR = "/home/ubuntu/vpn-credentials"
BASH_SCRIPTS_DIR = "/home/ubuntu/bash-scripts/Simulair-initialization-scripts"
CORE_PATH = "/home/ubuntu/simulair-core"
DEMO_CORE_PATH = "/5fad38003c71e979fe25839d"
MANAGER_PORT="3003"
PUBLIC_IP= None
PUBLIC_DNS_NAME = None
SIMULATION_ID = None
STATE_PATH="/home/ubuntu/.state"
STATE_FILE="state.json"
USER_RESOURCE_BUCKET_NAME="simulair-user-resources"
GLOBAL_RESOURCE_BUCKET_NAME="simulair-global-resources"
LOG_DIR='/home/ubuntu/.simlogs/log'